version: "3"
services:
  frontend:
    image: ironheade/prozell-frontend
    volumes:
      - ./src:/app/src
    #stdin_open: true
    ports: 
      - "8080:3000"
    networks:
      - prozell-app
    depends_on:
      - backend

  backend:
    image: ironheade/prozell-backend
    ports: 
      - "5000:5000"
    networks:
      - prozell-app

  app: 
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    ports:
      - '80:80'
      - '81:81'
      - '443:443'

networks:
  prozell-app:
    driver: bridge
