version: "3"
services:
  frontend:
    image: ironheade/prozell-frontend
    volumes:
      - ./src:/app/src
    #stdin_open: true
    ports: 
      - "8080:3000"
    networks:
      - prozell-app
    depends_on:
      - backend

  backend:
    image: ironheade/prozell-backend
    ports: 
      - "5000:5000"
    networks:
      - prozell-app

networks:
  prozell-app:
    driver: bridge
