version: "3"
services:
  frontend:
    image: ironheade/prozell-frontend
    container_name: ironheade-prozell-frontend
    ports: 
      - "8080:3000"
    networks:
      - nginxproxymanager_default
    depends_on:
      - backend

  backend:
    image: ironheade/prozell-backend
    container_name: backend
    ports: 
      - "5000:5000"
    networks:
      - nginxproxymanager_default
    volumes:
      - ./api/Datenbank.db:/api/Datenbank.db
      - ./api/passwort.db:/api/passwort.db

networks:
  nginxproxymanager_default:
    name: nginxproxymanager_default
    driver: bridge
